### ISSUE TITLE
Update SDK to 2.x with blocking API's as focus

### ISSUE THREAD

**Issue by Astaelan** [signalwire/signalwire-dotnet#22]
- [x] Review final proposal from SDK team for 2.x
- [x] Flesh out this list based on final SDK proposal for 2.x
- [x] Refactor and rename existing async API's as appropriate
- [x] Add new blocking API's that wait as appropriate
- [x] Update tests to use new Consumer model
- [x] Document new API's
- [x] Release 2.0 package
